collision:
  robot_radius: 0.05
  activation_distance: 0.45
  planning_min_distance: 0.05
  enable_self_collision: false

fcl_todo:
  broadphase_manager: DynamicAABBTreeCollisionManager
  request_nearest_points: true
  request_signed_distance: false

